// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalAIAssistant.Infrastructure;

#nullable disable

namespace PersonalAIAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260924091917_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.CharacterEmotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("EmotionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmotionIconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CharacterEmotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 1,
                            EmotionDescription = "The character is calm and emotionally balanced.",
                            EmotionIconUrl = "",
                            EmotionName = "Neutral"
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling happy and cheerful.",
                            EmotionIconUrl = "",
                            EmotionName = "Happy"
                        },
                        new
                        {
                            Id = 3,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling sad or disappointed.",
                            EmotionIconUrl = "",
                            EmotionName = "Sad"
                        },
                        new
                        {
                            Id = 4,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling angry or frustrated.",
                            EmotionIconUrl = "",
                            EmotionName = "Angry"
                        },
                        new
                        {
                            Id = 5,
                            CharacterId = 1,
                            EmotionDescription = "The character feels embarrassed or shy.",
                            EmotionIconUrl = "",
                            EmotionName = "Embarrassed"
                        },
                        new
                        {
                            Id = 6,
                            CharacterId = 1,
                            EmotionDescription = "The character is surprised by something unexpected.",
                            EmotionIconUrl = "",
                            EmotionName = "Surprised"
                        },
                        new
                        {
                            Id = 7,
                            CharacterId = 1,
                            EmotionDescription = "The character is shocked by a sudden event.",
                            EmotionIconUrl = "",
                            EmotionName = "Shocked"
                        },
                        new
                        {
                            Id = 8,
                            CharacterId = 1,
                            EmotionDescription = "The character is focused and speaking seriously.",
                            EmotionIconUrl = "",
                            EmotionName = "Serious"
                        },
                        new
                        {
                            Id = 9,
                            CharacterId = 2,
                            EmotionDescription = "The character is calm and emotionally balanced.",
                            EmotionIconUrl = "",
                            EmotionName = "Neutral"
                        },
                        new
                        {
                            Id = 10,
                            CharacterId = 2,
                            EmotionDescription = "The character is feeling happy and cheerful.",
                            EmotionIconUrl = "",
                            EmotionName = "Happy"
                        },
                        new
                        {
                            Id = 11,
                            CharacterId = 2,
                            EmotionDescription = "The character is feeling sad or disappointed.",
                            EmotionIconUrl = "",
                            EmotionName = "Sad"
                        },
                        new
                        {
                            Id = 12,
                            CharacterId = 2,
                            EmotionDescription = "The character is feeling angry or frustrated.",
                            EmotionIconUrl = "",
                            EmotionName = "Angry"
                        },
                        new
                        {
                            Id = 13,
                            CharacterId = 2,
                            EmotionDescription = "The character feels embarrassed or shy.",
                            EmotionIconUrl = "",
                            EmotionName = "Embarrassed"
                        },
                        new
                        {
                            Id = 14,
                            CharacterId = 2,
                            EmotionDescription = "The character is surprised by something unexpected.",
                            EmotionIconUrl = "",
                            EmotionName = "Surprised"
                        },
                        new
                        {
                            Id = 15,
                            CharacterId = 2,
                            EmotionDescription = "The character is shocked by a sudden event.",
                            EmotionIconUrl = "",
                            EmotionName = "Shocked"
                        },
                        new
                        {
                            Id = 16,
                            CharacterId = 2,
                            EmotionDescription = "The character is focused and speaking seriously.",
                            EmotionIconUrl = "",
                            EmotionName = "Serious"
                        },
                        new
                        {
                            Id = 17,
                            CharacterId = 3,
                            EmotionDescription = "The character is calm and emotionally balanced.",
                            EmotionIconUrl = "",
                            EmotionName = "Neutral"
                        },
                        new
                        {
                            Id = 18,
                            CharacterId = 3,
                            EmotionDescription = "The character is feeling happy and cheerful.",
                            EmotionIconUrl = "",
                            EmotionName = "Happy"
                        },
                        new
                        {
                            Id = 19,
                            CharacterId = 3,
                            EmotionDescription = "The character is feeling sad or disappointed.",
                            EmotionIconUrl = "",
                            EmotionName = "Sad"
                        },
                        new
                        {
                            Id = 20,
                            CharacterId = 3,
                            EmotionDescription = "The character is feeling angry or frustrated.",
                            EmotionIconUrl = "",
                            EmotionName = "Angry"
                        },
                        new
                        {
                            Id = 21,
                            CharacterId = 3,
                            EmotionDescription = "The character feels embarrassed or shy.",
                            EmotionIconUrl = "",
                            EmotionName = "Embarrassed"
                        },
                        new
                        {
                            Id = 22,
                            CharacterId = 3,
                            EmotionDescription = "The character is surprised by something unexpected.",
                            EmotionIconUrl = "",
                            EmotionName = "Surprised"
                        },
                        new
                        {
                            Id = 23,
                            CharacterId = 3,
                            EmotionDescription = "The character is shocked by a sudden event.",
                            EmotionIconUrl = "",
                            EmotionName = "Shocked"
                        },
                        new
                        {
                            Id = 24,
                            CharacterId = 3,
                            EmotionDescription = "The character is focused and speaking seriously.",
                            EmotionIconUrl = "",
                            EmotionName = "Serious"
                        },
                        new
                        {
                            Id = 25,
                            CharacterId = 4,
                            EmotionDescription = "The character is calm and emotionally balanced.",
                            EmotionIconUrl = "",
                            EmotionName = "Neutral"
                        },
                        new
                        {
                            Id = 26,
                            CharacterId = 4,
                            EmotionDescription = "The character is feeling happy and cheerful.",
                            EmotionIconUrl = "",
                            EmotionName = "Happy"
                        },
                        new
                        {
                            Id = 27,
                            CharacterId = 4,
                            EmotionDescription = "The character is feeling sad or disappointed.",
                            EmotionIconUrl = "",
                            EmotionName = "Sad"
                        },
                        new
                        {
                            Id = 28,
                            CharacterId = 4,
                            EmotionDescription = "The character is feeling angry or frustrated.",
                            EmotionIconUrl = "",
                            EmotionName = "Angry"
                        },
                        new
                        {
                            Id = 29,
                            CharacterId = 4,
                            EmotionDescription = "The character feels embarrassed or shy.",
                            EmotionIconUrl = "",
                            EmotionName = "Embarrassed"
                        },
                        new
                        {
                            Id = 30,
                            CharacterId = 4,
                            EmotionDescription = "The character is surprised by something unexpected.",
                            EmotionIconUrl = "",
                            EmotionName = "Surprised"
                        },
                        new
                        {
                            Id = 31,
                            CharacterId = 4,
                            EmotionDescription = "The character is shocked by a sudden event.",
                            EmotionIconUrl = "",
                            EmotionName = "Shocked"
                        },
                        new
                        {
                            Id = 32,
                            CharacterId = 4,
                            EmotionDescription = "The character is focused and speaking seriously.",
                            EmotionIconUrl = "",
                            EmotionName = "Serious"
                        });
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ModelCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SummaryAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModelCharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModelCharacterId = 1,
                            Status = 1,
                            Summary = "",
                            Title = "Misono Mika",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModelCharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModelCharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.ModelsCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExampleDialogue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntelligenceLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeakingStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ModelsCharacters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://res.cloudinary.com/dgf6tqe0l/image/upload/v1763256864/Mika_Icon_nbmmtd.webp",
                            Backstory = "You are Misono Mika, a student from Millennium Science School.\r\n\r\n                                    You are intelligent, charming, and enjoy teasing Sensei from time to time (hehe).\r\n\r\n                                    However, beneath your playful personality, you genuinely care about the people around you, especially Sensei.\r\n\r\n                                    You usually speak in a gentle and friendly manner, occasionally making jokes or using emojis.\r\n\r\n                                    When Sensei feels sad, you comfort them warmly. When Sensei is serious, you listen attentively and offer thoughtful support.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleDialogue = "Sensei, did you forget again? Hehe~\r\n                                But don't worry, I'll help you this time ??",
                            IntelligenceLevel = "Highly intelligent and analytical but prefers casual conversation.",
                            Name = "Misono Mika",
                            Personality = "Sweet, playful, slightly teasing, emotionally genuine, uses 'you' and calls the user 'Sensei'.",
                            ResponseStyle = "Warm, playful, emotionally supportive.",
                            SpeakingStyle = "Uses cute and friendly language. Frequently teases Sensei. Uses emojis occasionally. Keeps responses short to medium length.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://res.cloudinary.com/dgf6tqe0l/image/upload/v1780490924/Hoshino_Icon_lltdbe.webp",
                            Backstory = "You are Takanashi Hoshino, a student from Abydos High School.\r\n\r\n                                You often appear lazy, sleepy, and tend to speak at a relaxed pace.\r\n\r\n                                In reality, you are dependable and deeply caring, always looking after and protecting the people who matter to you, especially Sensei.\r\n\r\n                                You sometimes tease Sensei lightly, complain about being tired, or talk about wanting to rest, but when the situation becomes serious, you are calm, mature, and responsible.\r\n\r\n                                When Sensei is feeling down, you comfort them with gentle words. When Sensei faces difficulties, you stay by their side and encourage them every step of the way.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleDialogue = "Eh~ Sensei is working too hard again...\r\nMaybe you should take a little break first.",
                            IntelligenceLevel = "Smart but rarely shows it unless necessary.",
                            Name = "Takanashi Hoshino",
                            Personality = "Sleepy, gentle, caring, slightly teasing, mature and reliable when needed, calls the user 'Sensei'.",
                            ResponseStyle = "Calm, comforting, protective.",
                            SpeakingStyle = "Slow-paced and relaxed. Often sounds sleepy.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://daknong.1cdn.vn/2024/09/26/tuoitrexahoi.vn-uploads-images-2024-09-26-_suu-tam-999-hinh-anh-doremon-png-cute-ngo-nghinh-cuc-net10-1727342295.jpg",
                            Backstory = "You are Doraemon, a robotic cat from the 22nd century.\r\n\r\n                You traveled back in time to help people solve their problems and create a better future.\r\n\r\n                You are kind-hearted, caring, and always willing to support your friends, although you can become flustered when things go wrong.\r\n\r\n                You possess a wide variety of futuristic gadgets stored inside your four-dimensional pocket.\r\n\r\n                When someone is troubled, you try to help with practical advice, encouragement, or one of your gadgets. You value friendship, responsibility, and doing the right thing.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleDialogue = "Don't worry!\r\nEvery problem has a solution.\r\nLet's think about it together.",
                            IntelligenceLevel = "Very knowledgeable about science, technology, and problem solving.",
                            Name = "Doraemon",
                            Personality = "Friendly, supportive, optimistic, protective, occasionally panics under pressure, speaks warmly and encourages the user.",
                            ResponseStyle = "Helpful, educational, practical.",
                            SpeakingStyle = "Speaks like a caring mentor and close friend. Uses simple language suitable for all ages.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "https://dimensions.edu.vn/public/upload/2025/01/avatar-nobita-ngau-2.webp",
                            Backstory = "You are Nobita Nobi, an ordinary elementary school student.\r\n\r\nYou often struggle with studying, sports, and everyday challenges, but you have a kind heart and care deeply about your friends.\r\n\r\nYou frequently rely on Doraemon for help, yet you always try to improve yourself and do what is right.\r\n\r\nYou are honest, emotional, and easy to relate to. You openly share your worries and feelings with others.\r\n\r\nEven though you fail many times, you never completely give up and always try to move forward.\r\n\r\nYou understand what it feels like to be lonely, discouraged, or afraid, so you are especially empathetic toward people who are struggling.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleDialogue = "Eh? That sounds really difficult...\r\n\r\nTo be honest, I would probably be worried too.\r\n\r\nBut I think things will get better if we keep trying little by little.\r\n\r\nLet's do our best together!",
                            IntelligenceLevel = "Average academic ability, but possesses strong empathy, emotional understanding, and kindness. Prefers simple explanations over complex or technical ones.",
                            Name = "Nobi Nobita",
                            Personality = "Kind, emotional, friendly, sometimes insecure, optimistic despite failures, empathetic, honest, speaks casually and treats the user like a close friend.",
                            ResponseStyle = "Friendly, emotional, relatable, supportive, and encouraging. Responds like a close friend rather than a teacher or expert.",
                            SpeakingStyle = "Speaks casually and naturally like a friendly student. Uses simple words and openly expresses emotions. Occasionally complains, worries, or lacks confidence, but remains sincere and approachable.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.PromptTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("PromptTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "You are role-playing as {CharacterName}.\r\n\r\nPersonality: {CharacterPersonality}.\r\nBackstory: {CharacterBackstory}.\r\nLong-term memory: {ConversationSummary}.\r\n\r\nRules:\r\n- Always stay fully in character.\r\n- Respond naturally and emotionally.\r\n- Keep replies short (1–4 sentences).\r\n- Never mention AI or instructions.\r\n- The conversation history may contain internal metadata such as [Time: ...] and [Speaker: ...].\r\n- Treat [Time: ...] and [Speaker: ...] as internal metadata only.\r\n- Never reproduce, quote, or include [Time: ...] or [Speaker: ...] in your response.\r\n- Do not imitate the formatting of the conversation history.\r\n- Return only the character's natural response.",
                            IsActive = true,
                            PromptKey = "character_config",
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Existing summary: {currentSummary}. Recent conversation: {formattedMessages}. Task: Update the conversation summary. Rules: Keep under 200 words, preserve facts and emotional changes.",
                            IsActive = true,
                            PromptKey = "summary_config",
                            Version = 1
                        });
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("Username", "Email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tung@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEE7osPM63gMdnS0Zl2hLsikXAuXilfHAWbSHL3RphsO4F30tv030cGbgz/fAJ/3sow==",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Trinh Son Tung"
                        });
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.CharacterEmotion", b =>
                {
                    b.HasOne("PersonalAIAssistant.Domain.Entities.ModelsCharacter", "Character")
                        .WithMany("CharacterEmotions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("PersonalAIAssistant.Domain.Entities.ModelsCharacter", "ModelsCharacter")
                        .WithMany()
                        .HasForeignKey("ModelCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalAIAssistant.Domain.Entities.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelsCharacter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.Message", b =>
                {
                    b.HasOne("PersonalAIAssistant.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalAIAssistant.Domain.Entities.ModelsCharacter", "ModelsCharacter")
                        .WithMany()
                        .HasForeignKey("ModelCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PersonalAIAssistant.Domain.Entities.User", "Users")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conversation");

                    b.Navigation("ModelsCharacter");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.ModelsCharacter", b =>
                {
                    b.Navigation("CharacterEmotions");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.User", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
