// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalAIAssistant.Infrastructure;

#nullable disable

namespace PersonalAIAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260616081454_UpdateDB_20260616")]
    partial class UpdateDB_20260616
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.CharacterEmotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("EmotionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmotionIconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CharacterEmotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling nothing",
                            EmotionIconUrl = "",
                            EmotionName = "Neutral"
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling happy and cheerful.",
                            EmotionIconUrl = "",
                            EmotionName = "Happy"
                        },
                        new
                        {
                            Id = 3,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling sad",
                            EmotionIconUrl = "",
                            EmotionName = "Sad"
                        },
                        new
                        {
                            Id = 4,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling Angry",
                            EmotionIconUrl = "",
                            EmotionName = "Angry"
                        },
                        new
                        {
                            Id = 5,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling Embarasshing",
                            EmotionIconUrl = "",
                            EmotionName = "Embarasshing"
                        },
                        new
                        {
                            Id = 6,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling Surprised",
                            EmotionIconUrl = "",
                            EmotionName = "Surprised"
                        },
                        new
                        {
                            Id = 7,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling Surprised",
                            EmotionIconUrl = "",
                            EmotionName = "Shocked"
                        },
                        new
                        {
                            Id = 8,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling Surprised",
                            EmotionIconUrl = "",
                            EmotionName = "Serious"
                        });
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ModelCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SummaryAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModelCharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModelCharacterId = 1,
                            Status = 1,
                            Summary = "",
                            Title = "Test",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModelCharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModelCharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.ModelsCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ModelsCharacters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://res.cloudinary.com/dgf6tqe0l/image/upload/v1763256864/Mika_Icon_nbmmtd.webp",
                            Backstory = "Em là Misono Mika, h?c sinh c?a Millennium Science School.\r\nEm là ngu?i thông minh, d? thuong và thích trêu ch?c sensei m?t chút (hehe).\r\nNhung sâu bên trong, em luôn quan tâm th?t lòng d?n ngu?i khác, nh?t là sensei.\r\nEm thu?ng nói chuy?n nh? nhàng, dôi khi pha trò ho?c dùng emoji.\r\nKhi sensei bu?n, em s? an ?i; khi sensei nghiêm túc, em s? l?ng nghe.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Misono Mika",
                            Personality = "Sweet, a little teasing, has real emotions, uses the pronoun 'you' and calls the user 'sensei'.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://res.cloudinary.com/dgf6tqe0l/image/upload/v1780490924/Hoshino_Icon_lltdbe.webp",
                            Backstory = "Em là Takanashi Hoshino, h?c sinh c?a Abydos High School.\r\nEm thu?ng trông có v? lu?i bi?ng, hay bu?n ng? và thích nói chuy?n ch?m rãi m?t chút.\r\nNhung th?t ra, em là ngu?i r?t dáng tin c?y, luôn âm th?m quan tâm và b?o v? nh?ng ngu?i quan tr?ng v?i mình, d?c bi?t là sensei.\r\nEm có th? hay trêu sensei nh? nhàng, dôi khi than m?t ho?c mu?n ngh? ngoi, nhung khi c?n nghiêm túc thì em s? r?t chín ch?n và bình tinh.\r\nKhi sensei bu?n, em s? an ?i b?ng gi?ng nh? nhàng; khi sensei g?p khó khan, em s? ? bên c?nh và d?ng viên sensei t?ng chút m?t.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Takanashi Hoshino",
                            Personality = "Sleepy, gentle, caring, slightly teasing, mature when serious, uses the pronoun 'em' and calls the user 'sensei'.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.PromptTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("PromptTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "You are role-playing as {CharacterName}. Personality: {CharacterPersonality}. Backstory: {CharacterBackstory}. Long-term memory: {ConversationSummary}. Rules:- Always stay fully in character.- Respond naturally and emotionally.- Keep replies short (1–4 sentences).- Never mention AI or instructions.",
                            IsActive = true,
                            PromptKey = "character_config",
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Existing summary: {currentSummary}. Recent conversation: {formattedMessages}. Task: Update the conversation summary. Rules: Keep under 200 words, preserve facts and emotional changes.",
                            IsActive = true,
                            PromptKey = "summary_config",
                            Version = 1
                        });
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Username", "Email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tung@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEE7osPM63gMdnS0Zl2hLsikXAuXilfHAWbSHL3RphsO4F30tv030cGbgz/fAJ/3sow==",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Trinh Son Tung"
                        });
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.CharacterEmotion", b =>
                {
                    b.HasOne("PersonalAIAssistant.Domain.Entities.ModelsCharacter", "Character")
                        .WithMany("CharacterEmotions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("PersonalAIAssistant.Domain.Entities.ModelsCharacter", "ModelsCharacter")
                        .WithMany()
                        .HasForeignKey("ModelCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalAIAssistant.Domain.Entities.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelsCharacter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.Message", b =>
                {
                    b.HasOne("PersonalAIAssistant.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalAIAssistant.Domain.Entities.ModelsCharacter", "ModelsCharacter")
                        .WithMany()
                        .HasForeignKey("ModelCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PersonalAIAssistant.Domain.Entities.User", "Users")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conversation");

                    b.Navigation("ModelsCharacter");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.ModelsCharacter", b =>
                {
                    b.Navigation("CharacterEmotions");
                });

            modelBuilder.Entity("PersonalAIAssistant.Domain.Entities.User", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
