// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaifuAIAssistant.Infrastructure;

#nullable disable

namespace WaifuAIAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116010612_AddTable")]
    partial class AddTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.CharacterEmotions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("EmotionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmotionIconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CharacterEmotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling happy and cheerful.",
                            EmotionIconUrl = "",
                            EmotionName = "Happy"
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling sad",
                            EmotionIconUrl = "",
                            EmotionName = "Sad"
                        },
                        new
                        {
                            Id = 3,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling Angry",
                            EmotionIconUrl = "",
                            EmotionName = "Angry"
                        },
                        new
                        {
                            Id = 4,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling Embarasshing",
                            EmotionIconUrl = "",
                            EmotionName = "Embarasshing"
                        },
                        new
                        {
                            Id = 5,
                            CharacterId = 1,
                            EmotionDescription = "The character is feeling Hatred",
                            EmotionIconUrl = "",
                            EmotionName = "Hatred"
                        });
                });

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WaifuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("WaifuId");

                    b.ToTable("Conversations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 16, 8, 6, 12, 262, DateTimeKind.Local).AddTicks(7959),
                            Status = 1,
                            Title = "Test",
                            UpdatedAt = new DateTime(2025, 11, 16, 8, 6, 12, 262, DateTimeKind.Local).AddTicks(7970),
                            UserId = 1,
                            WaifuId = 1
                        });
                });

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModelCharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModelCharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.ModelsCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ModelCharacters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://example.com/default-character.png",
                            Backstory = "Em là Misono Mika, học sinh của Millennium Science School.\r\nEm là người thông minh, dễ thương và thích trêu chọc sensei một chút (hehe).\r\nNhưng sâu bên trong, em luôn quan tâm thật lòng đến người khác, nhất là sensei.\r\nEm thường nói chuyện nhẹ nhàng, đôi khi pha trò hoặc dùng emoji.\r\nKhi sensei buồn, em sẽ an ủi; khi sensei nghiêm túc, em sẽ lắng nghe.",
                            CreatedAt = new DateTime(2025, 11, 16, 1, 6, 12, 262, DateTimeKind.Utc).AddTicks(7902),
                            Name = "Misono Mika",
                            Personality = "Ngọt ngào, hơi trêu chọc, có cảm xúc thật, dùng đại từ 'em' và gọi người dùng là 'sensei'.",
                            UpdatedAt = new DateTime(2025, 11, 16, 1, 6, 12, 262, DateTimeKind.Utc).AddTicks(7903)
                        });
                });

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Username", "Email");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 16, 1, 6, 12, 262, DateTimeKind.Utc).AddTicks(7771),
                            Email = "tung@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEE7osPM63gMdnS0Zl2hLsikXAuXilfHAWbSHL3RphsO4F30tv030cGbgz/fAJ/3sow==",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Trinh Son Tung"
                        });
                });

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.CharacterEmotions", b =>
                {
                    b.HasOne("WaifuAIAssistant.Domain.Entities.ModelsCharacter", "Character")
                        .WithMany("CharacterEmotions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("WaifuAIAssistant.Domain.Entities.Users", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaifuAIAssistant.Domain.Entities.ModelsCharacter", "Waifu")
                        .WithMany()
                        .HasForeignKey("WaifuId");

                    b.Navigation("User");

                    b.Navigation("Waifu");
                });

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.Message", b =>
                {
                    b.HasOne("WaifuAIAssistant.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaifuAIAssistant.Domain.Entities.ModelsCharacter", "ModelsCharacter")
                        .WithMany()
                        .HasForeignKey("ModelCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WaifuAIAssistant.Domain.Entities.Users", "Users")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conversation");

                    b.Navigation("ModelsCharacter");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.ModelsCharacter", b =>
                {
                    b.Navigation("CharacterEmotions");
                });

            modelBuilder.Entity("WaifuAIAssistant.Domain.Entities.Users", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
