name: Build & Deploy Azure VM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t tungtrinh2003/devop:latest .
    - name: Push the Docker image
      run: docker push tungtrinh2003/devop:latest
    - name: Deploy on Azure VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          sudo docker pull tungtrinh2003/devop:latest
          sudo docker stop devop || true
          sudo docker rm devop || true
          sudo docker run -d --name devop -p 8080:8080 tungtrinh2003/devop:latest